# 数据库连接配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/digital_twin?useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=3522021@Hx

# 打印 MyBatis-Plus 生成的 SQL 日志（方便你观察）
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl