package org.example.springbootmpdemo;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication(scanBasePackages = "org.example.springbootmpdemo")
public class SpringbootMpDemoApplication{

    @Autowired
    private DeviceMapper mapper;
    public static void main(String[] args) {
        SpringApplication.run(SpringbootMpDemoApplication.class, args);
    }

}
